Menu api
BPEssentials/BP-CoreLib pull request #3
Opened 2020-10-22 18:27 UTC by ggggg

2020-10-22 18:29 UTC, ggggg commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +    public class OptionMenu
Should make it internal tbh

2020-10-22 18:31 UTC, PLASMAchicken requested changes

2020-10-22 18:31 UTC, PLASMAchicken commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +        public Action<ShPlayer, string> action;
Shouldn't this be Name and Action

2020-10-22 18:31 UTC, PLASMAchicken commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +    public class OnStarted : IScript
Why this name?

2020-10-22 18:31 UTC, PLASMAchicken commented on src/BP-CoreLib/BP-CoreLib.csproj
> +    <Compile Include="OptionMenu\ActionLabel.cs" />
Interface?

2020-10-23 17:49 UTC, ggggg commented on src/BP-CoreLib/BP-CoreLib.csproj
> +    <Compile Include="OptionMenu\ActionLabel.cs" />
Good idea

2020-10-23 18:39 UTC, PLASMAchicken approved these changes

2020-10-23 22:44 UTC, UserR00T requested changes
Looking good, the-g! I have a few minor changes but nothing too much.

2020-10-23 22:44 UTC, UserR00T commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +            this.Action = action;
`this.` is not required here.
```suggestion
            Name = name;
            Action = action;
```

2020-10-23 22:44 UTC, UserR00T commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +        private readonly string menuId;
Inconsistent field naming. private readonly fields should be camelCased, prefixed with a `_`.
```suggestion
        private readonly string _title;
        public Dictionary<string, ActionLabel> Actions { get; private set; }
        private readonly LabelID[] _options;
        private readonly string _menuId;
```

2020-10-23 22:44 UTC, UserR00T commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +        public static Dictionary<string, OptionMenu> Menus = new Dictionary<string, OptionMenu>();
Pull field upwards.

2020-10-23 22:44 UTC, UserR00T commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +            }
Could be converted to a for loop so you can inline the `i` variable.

2020-10-23 22:44 UTC, UserR00T commented on src/BP-CoreLib/OptionMenu/ActionLabel.cs
> +            (new OptionMenu(title, labels, actions)).SendToPlayer(player);
Instantly disposed POCO's are not a good idea. While I do currently not have a solution in this case, keep this in mind for next time.

2020-10-24 04:31 UTC, ggggg reviewed
Hey, root! Glad to hear from you again. I made some changes to fit your suggestions and also changed the array to take in IEnumerable. I hope this is good now for marge.

2020-10-24 14:31 UTC, UserR00T approved these changes
LGTM! :)

2020-10-24 14:32 UTC, merged